"""Public Firebase API for user management."""

from .firebase import (
    initialize_firebase,
    get_database_status,
    create_user_record,
    ensure_user_account_id,
    get_user_record,
    get_user_record_for_account_deletion,
    delete_user_account,
    get_ai_selection,
    save_ai_selection,
    create_nutrition_entry,
    delete_nutrition_entry,
    list_nutrition_entries,
    update_nutrition_entry,
    delete_ai_credential,
    delete_ai_credential_for_account_deletion,
    delete_all_ai_credentials,
    delete_openai_credential,
    get_ai_credential,
    get_ai_credential_status,
    get_openai_credential,
    get_openai_credential_status,
    save_ai_credential,
    save_openai_credential,
)
